### ISSUE TITLE
Mapping problem

### ISSUE THREAD

**Issue by aciechomski** [MoonStorm/Dapper.FastCRUD#125]
.SetProperty( a => a.Address.City, prop => prop.SetDatabaseColumnName("City"));

Exception has occurred: CLR/System.InvalidOperationException
An exception of type 'System.InvalidOperationException' occurred in System.Linq.dll but was not handled in user code: 'Sequence contains no matching element'
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Dapper.FastCrud.Mappings.EntityMapping.SetPropertyInternal(String propertyName) in D:\a\1\s\Dapper.FastCrud\Mappings\EntityMapping.cs:line 154

**Comment by MoonStorm** [comment]
Closing due to inactivity.
