### ISSUE TITLE
GetAsync() and Include

### ISSUE THREAD

**Issue by ravenpride** [MoonStorm/Dapper.FastCRUD#54]
There seems to be an issue with the GetAsync() method. I'm writing a small library to maintain the database of my private mail server and tried to query a SQLite database. The "MailAccount" class contains a property to the "Domain" the mail account belongs to. Furthermore a property of type _long_ annotated with the _ForeignKey_ attribute points to the "Domain" property.

The following line works as expected:
`MailAccount account = connection.Get(new MailAccount { Id = id }, statements =>statements.Include<Domain>(x => x.LeftOuterJoin()));`

The asynchronous equivalent does not:
`MailAccount account = await connection.GetAsync<MailAccount>(new MailAccount { Id = id }, statements => statements.Include<Domain>(x => x.LeftOuterJoin()));`

Is there something I should additionally consider when using the asynchronous API functions?

**Comment by MoonStorm** [comment]
What issue are you experiencing?

**Comment by ravenpride** [comment]
An InvalidOperationException is thrown when calling GetAsync(). 

Exception Text:
`Invalid attempt to call FieldCount when reader is closed.`

Stack Trace:
```
   at Microsoft.Data.Sqlite.SqliteDataReader.get_FieldCount()
   at Dapper.SqlMapper.GetColumnHash(IDataReader reader, Int32 startBound, Int32 length)
   at Dapper.SqlMapper.<MultiMapImpl>d__139`8.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Dapper.FastCrud.SqlStatements.RelationshipSqlStatements`1.<SelectByIdAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CloudyCube.Api.Persistence.Repositories.MailAccountRepository.<GetByIdAsync>d__3.MoveNext() in D:\Visual Studio Projects\CloudyCube\CloudyCube\src\ManagerAPI\Persistence\Repositories\MailAccountRepository.cs:line 59
```

Oh. if it matters, I'm using .NET Core 1.0.1.

**Comment by MoonStorm** [comment]
Dapper is suffering from a [bug](https://github.com/StackExchange/dapper-dot-net/issues/596) that causes the async methods to fail.

**Comment by ravenpride** [comment]
Ok, I'll try to work around it. Thank you very much for the explanation!

**Comment by generik0** [comment]
Hi.
I am having the same issue. But i get:
"<System.InvalidOperationException: No columns were selected". 

The normal Get works, but not the async.

![image](https://cloud.githubusercontent.com/assets/2411563/21115394/5ac70e20-c0b1-11e6-9cde-583cfb50618f.png)

**Comment by generik0** [comment]
Workaround :-(
<pre><code>
public Task<QuotationItem> GetIdAsync( int id, ISession session)
{
        SetDialogue<Product>(session);
        return Task.Run(() => GetId(id, session));
}</pre></code>

**Comment by GroundZero** [comment]
@generik0 Please mark It as 'Workaround if you are super retarded and dumb and want you application to suck'. Maybe even underline It.

Do you know that  GetId will block and you will block one of the very important threads for the Task Scheduler? You didn't even use long running flag so It's super likely to completly shutdown your application If your application.

For anyone looking at this **DO NOT USE IT!** It will cause alot of unwanted behvaiour.

**Comment by generik0** [comment]
Omg. What language you have young man.
It isn't nice to call people "super retarded".

If you are a better programmer then it is best to give an example of how to do it.

But as far as I know.

Calling 
var actual = await foo.GetIdAsync(1, session);
Shouldn't block. 
Yes it will use a thread in the thread pool. But that is it.

Have a look at who to make async methods:
https://msdn.microsoft.com/en-us/library/hh873177(v=vs.110).aspx

<pre><code>
internal Task<Bitmap> RenderAsync(
              ImageData data, CancellationToken cancellationToken)
{
    return Task.Run(() =>
    {
        var bmp = new Bitmap(data.Width, data.Height);
        for(int y=0; y<data.Height; y++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            for(int x=0; x<data.Width; x++)
            {
                // render pixel [x,y] into bmp
            }
        }
        return bmp;
    }, cancellationToken);
}
</code></pre>

**Comment by generik0** [comment]
@GroundZero Any Comments?

**Comment by sachindk1625** [comment]
I'm still facing this issue

An InvalidOperationException is thrown when calling GetAsync().

Exception Text:
`Invalid attempt to call FieldCount when reader is closed.`
