### ISSUE TITLE
Sql Server 2008 "Invalid usage of the option NEXT in the FETCH statement."

### ISSUE THREAD

**Issue by AdhamAwadhi** [MoonStorm/Dapper.FastCRUD#85]
Hi,
I'm using SQL Server 2008 and querying using this
```
cn.FindAsync<SmsMessage>(statement => statement
                                      .Where($"{nameof(SmsMessage.State):C} = 0 AND LEN({nameof(SmsMessage.Mobile):C}) BETWEEN @PhoneLengthMin AND @PhoneLengthMax AND {nameof(SmsMessage.EnterTime):C} >= @messageTime")
                                      .OrderBy($"{nameof(SmsMessage.Id):C}")
                                      .Skip((page - 1) * pageSize)
                                      .Top(pageSize)
                                      .WithParameters(new { PhoneLengthMin = _phoneLengthMin, PhoneLengthMax = _phoneLengthMax, messageTime = messageTime }))
```
But I got an error

>  **"Invalid usage of the option NEXT in the FETCH statement."**

**Comment by MoonStorm** [comment]
SQL Server 2008 might need a separate dialect. I don't have that version installed so I can't test it. What is the generated SQL?

**Comment by AdhamAwadhi** [comment]
I searched for this issue and I found Sql Server 2008 does not support FETCH.
This the generated SQL: 
  ```  
 exec sp_executesql N'SELECT [Id],[MessageText] AS [Text],[Receiver] AS [Mobile],[State],[ReturnData] AS [Result],[EnterTime] FROM [tblSMS_Messages] WHERE [State] = 0 AND LEN([Receiver]) BETWEEN @PhoneLengthMin AND @PhoneLengthMax AND [EnterTime] >= @messageTime ORDER BY [Id] OFFSET 0 ROWS FETCH NEXT 32 ROWS ONLY',N'@PhoneLengthMin tinyint,@PhoneLengthMax tinyint,@messageTime datetime',@PhoneLengthMin=9,@PhoneLengthMax=12,@messageTime='2017-05-12 15:15:59.500'
 ```
I worked around it using this :
 ```
var sqlBuilder = OrmConfiguration.GetSqlBuilder<SmsMessage>();
            var query =  sqlBuilder.Format(
           $@"
SELECT {sqlBuilder.ConstructColumnEnumerationForSelect()}
FROM(SELECT    ROW_NUMBER() OVER(ORDER BY Id) AS RowNum, *
          FROM      {sqlBuilder.GetTableName()}
          WHERE		{nameof(SmsMessage.State):C} = 0 AND LEN({nameof(SmsMessage.Mobile):C}) BETWEEN @PhoneLengthMin AND @PhoneLengthMax AND {nameof(SmsMessage.EnterTime):C} >= @messageTime
        ) AS result
WHERE RowNum > @skippedItems
    AND RowNum <= @skippedItems + @pageSize
ORDER BY RowNum");
cn.QueryAsync<SmsMessage>(query,
                            new
                            {
                                PhoneLengthMin = _phoneLengthMin,
                                PhoneLengthMax = _phoneLengthMax,
                                messageTime = messageTime,
                                skippedItems = (page - 1) * pageSize,
                                pageSize = pageSize
                            });
```

**Comment by vantian** [comment]
I got same issue, I dont think it's because Sql Server 2008.
I tried both in Sql Server 2012 and Sql Azure and still got this exception

> Message: System.Data.SqlClient.SqlException : Incorrect syntax near '1'.
> Invalid usage of the option NEXT in the FETCH statement.

here's my query
`Connection.FindAsync<TEntity>(statement => statement.Skip(0).Top(5));`

I'm using Dotnetcore 1.1

**Comment by dotnetchris** [comment]
I encountered this error when running against an old SQL 2008 R2 server. I installed SQL Express 17 on my box and the error went away.

**Comment by ArtistNeverStop** [comment]
Excecuting the "sequeIize.authenticate"  method  inmediatly after initialization resolves the problem for me.  I dont know what is happening here but, I was stock on the same error.
`
SequelizeDatabaseError: Invalid usage of the option NEXT in the FETCH statement.
    at Query.formatError (C:\xampp\htdocs\Benoit\node_modules\sequelize\lib\dialects\mssql\query.js:315:12)
    at Request.connection.lib.Request [as userCallback] (C:\xampp\htdocs\Benoit\node_modules\sequelize\lib\dialects\mssql\query.js:107:25)
    at Request._this.callback (C:\xampp\htdocs\Benoit\node_modules\tedious\lib\request.js:60:27)
    at Connection.endOfMessageMarkerReceived (C:\xampp\htdocs\Benoit\node_modules\tedious\lib\connection.js:1922:20)
    at Connection.dispatchEvent (C:\xampp\htdocs\Benoit\node_modules\tedious\lib\connection.js:1004:38)
    at Parser.<anonymous> (C:\xampp\htdocs\Benoit\node_modules\tedious\lib\connection.js:805:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at Parser.<anonymous> (C:\xampp\htdocs\Benoit\node_modules\tedious\lib\token\token-stream-parser.js:54:15)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at addChunk (C:\xampp\htdocs\Benoit\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (C:\xampp\htdocs\Benoit\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at Parser.Readable.push (C:\xampp\htdocs\Benoit\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at Parser.Transform.push (C:\xampp\htdocs\Benoit\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at Parser.afterTransform (C:\xampp\htdocs\Benoit\node_modules\readable-stream\lib\_stream_transform.js:91:10)
    at Parser._transform (C:\xampp\htdocs\Benoit\node_modules\tedious\lib\token\stream-parser.js:69:9)
    at Parser.Transform._read (C:\xampp\htdocs\Benoit\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at Parser.Transform._write (C:\xampp\htdocs\Benoit\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\xampp\htdocs\Benoit\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\xampp\htdocs\Benoit\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at Parser.Writable.write (C:\xampp\htdocs\Benoit\node_modules\readable-stream\lib\_stream_writable.js:334:11)
`
I got the error after a brief restructure of my code on a project, 
I realize that, just because the history of my sublime stored it, I was just deleting all the excess code in the project and the authenticated method was commented.

I dont know what is the relation between the initial authentication method and the grammar and syntax of the queries, I don't even think that must have a relation, but is what it is

**Comment by jjanne** [comment]
If you encounter this problem with Azure SQL, just change the Compatibility Level of your database to 130 or higher.  You can do this via script or SQL Server Management Studio by looking at the database properties->options.

**Comment by MoonStorm** [comment]
Currently looking at this but honestly we don't have the resources to maintain the tests for this old dinosaur.
